# Example queries: `invariants_three_way` (comstock_oedi_agg)

Auto-generated from `tests/query_snapshots/invariants_three_way.json`. Each cell
runs one entry from the snapshot suite. Regenerate by running the
matching test with `--update-snapshot` or `--overwrite-snapshot`.

In [1]:
from pathlib import Path
from buildstock_query import BuildStockQuery
import pandas as pd

## Construct the BuildStockQuery object

`cache_folder` points at the snapshot test cache directory so this
notebook reuses parquets that the test suite has already downloaded
from Athena. Queries that are already cached return immediately;
anything new still hits Athena.

In [2]:
# This notebook lives in `tests/example_notebooks/`; the snapshot test
# cache is its sibling `tests/query_snapshots/comstock_oedi_agg_cache/`. Resolve
# the path relative to the notebook directory (`_dh[0]` is set by
# IPython at kernel startup; falls back to CWD outside Jupyter).
_NB_DIR = Path(_dh[0] if "_dh" in globals() else ".").resolve()
_CACHE = (_NB_DIR / "../query_snapshots/comstock_oedi_agg_cache").resolve()
bsq = BuildStockQuery(
    "rescore",
    "buildstock_sdr",
    "comstock_amy2018_r2_2025",
    buildstock_type="comstock",
    db_schema="comstock_oedi_agg_state_and_county",
    skip_reports=True,
    cache_folder=str(_CACHE),
)

INFO:buildstock_query.query_core:Loading comstock_amy2018_r2_2025 ...

INFO:botocore.tokens:Loading cached SSO token for nrel-sso

## `inv_baseline_ts_year_by_building_type`

Three-way invariant: ts-year-collapse leg, baseline. Two fuels.

In [3]:
result = bsq.query(
    enduses=['out.electricity.total.energy_consumption', 'out.natural_gas.total.energy_consumption'],
    upgrade_id='0',
    annual_only=False,
    timestamp_grouping_func='year',
    group_by=['comstock_building_type'],
    restrict=[('state', ['CO'])],
)
result.head() if hasattr(result, 'head') else result

,comstock_building_type,sample_count,units_count,rows_per_sample,electricity.total.energy_consumption,natural_gas.total.energy_consumption
0,FullServiceRestaurant,2526,4556.431396,35040,1.209201e+09,1.192990e+09
1,Hospital,63,152.003100,35040,1.369473e+09,7.934667e+08
2,LargeHotel,1460,3317.336942,35040,1.128185e+09,9.205921e+08
3,LargeOffice,866,849.927533,35040,1.546956e+09,4.449978e+08
4,MediumOffice,2351,2418.404703,35040,1.298819e+09,4.003603e+08

## `inv_upgrade1_annual_by_building_type`

Three-way invariant: annual leg, upgrade 1 (no applied filter), CO. Two fuels.

In [4]:
result = bsq.query(
    enduses=['out.electricity.total.energy_consumption..kwh', 'out.natural_gas.total.energy_consumption..kwh'],
    upgrade_id='1',
    applied_only=False,
    group_by=['comstock_building_type'],
    restrict=[('state', ['CO'])],
)
result.head() if hasattr(result, 'head') else result

,comstock_building_type,sample_count,units_count,electricity.total.energy_consumption..kwh,natural_gas.total.energy_consumption..kwh
0,FullServiceRestaurant,2526,4556.431396,1.202904e+09,9.885149e+08
1,Hospital,63,152.003100,1.369473e+09,7.929358e+08
2,LargeHotel,1460,3317.336942,1.128185e+09,9.199770e+08
3,LargeOffice,866,849.927533,1.546063e+09,4.431886e+08
4,MediumOffice,2351,2418.404703,1.275959e+09,3.533251e+08

## `inv_upgrade1_ts_year_by_building_type`

Three-way invariant: ts-year-collapse leg, upgrade 1 (no applied filter). Two fuels.

In [5]:
result = bsq.query(
    enduses=['out.electricity.total.energy_consumption', 'out.natural_gas.total.energy_consumption'],
    upgrade_id='1',
    applied_only=False,
    annual_only=False,
    timestamp_grouping_func='year',
    group_by=['comstock_building_type'],
    restrict=[('state', ['CO'])],
)
result.head() if hasattr(result, 'head') else result

,comstock_building_type,sample_count,units_count,rows_per_sample,electricity.total.energy_consumption,natural_gas.total.energy_consumption
0,FullServiceRestaurant,2526,4556.431396,35040,1.202904e+09,9.891760e+08
1,Hospital,63,152.003100,35040,1.369473e+09,7.934667e+08
2,LargeHotel,1460,3317.336942,35040,1.128185e+09,9.205921e+08
3,LargeOffice,866,849.927533,35040,1.546063e+09,4.434853e+08
4,MediumOffice,2351,2418.404703,35040,1.275959e+09,3.535617e+08

## `inv_upgrade1_ts_monthly_by_building_type`

Three-way invariant: ts-monthly leg, upgrade 1 (no applied filter). Two fuels.

In [6]:
result = bsq.query(
    enduses=['out.electricity.total.energy_consumption', 'out.natural_gas.total.energy_consumption'],
    upgrade_id='1',
    applied_only=False,
    annual_only=False,
    timestamp_grouping_func='month',
    group_by=['comstock_building_type', 'time'],
    restrict=[('state', ['CO'])],
)
result.head() if hasattr(result, 'head') else result

,comstock_building_type,timestamp,sample_count,units_count,rows_per_sample,electricity.total.energy_consumption,natural_gas.total.energy_consumption
0,FullServiceRestaurant,2018-01-01,2526,4556.431396,2976,1.169248e+08,9.008933e+07
1,FullServiceRestaurant,2018-02-01,2526,4556.431396,2688,1.137267e+08,8.278133e+07
2,FullServiceRestaurant,2018-03-01,2526,4556.431396,2976,9.562731e+07,8.595782e+07
3,FullServiceRestaurant,2018-04-01,2526,4556.431396,2880,8.889165e+07,8.132115e+07
4,FullServiceRestaurant,2018-05-01,2526,4556.431396,2976,9.068696e+07,8.069483e+07

## `inv_upgrade1_applied_annual_by_building_type`

Three-way invariant: annual leg, upgrade 1, applied_only=True. Two fuels.

In [7]:
result = bsq.query(
    enduses=['out.electricity.total.energy_consumption..kwh', 'out.natural_gas.total.energy_consumption..kwh'],
    upgrade_id='1',
    applied_only=True,
    group_by=['comstock_building_type'],
    restrict=[('state', ['CO'])],
)
result.head() if hasattr(result, 'head') else result

,comstock_building_type,sample_count,units_count,electricity.total.energy_consumption..kwh,natural_gas.total.energy_consumption..kwh
0,FullServiceRestaurant,2056,4222.612917,1.067479e+09,9.065733e+08
1,LargeOffice,22,8.927070,6.772289e+06,4.943943e+04
2,MediumOffice,527,603.917258,1.684458e+08,3.609832e+06
3,Outpatient,408,1387.428142,1.513751e+08,1.429535e+07
4,PrimarySchool,475,1108.926331,2.838699e+08,5.203942e+07

## `inv_upgrade1_applied_ts_year_by_building_type`

Three-way invariant: ts-year-collapse leg, upgrade 1, applied_only=True. Two fuels.

In [8]:
result = bsq.query(
    enduses=['out.electricity.total.energy_consumption', 'out.natural_gas.total.energy_consumption'],
    upgrade_id='1',
    applied_only=True,
    annual_only=False,
    timestamp_grouping_func='year',
    group_by=['comstock_building_type'],
    restrict=[('state', ['CO'])],
)
result.head() if hasattr(result, 'head') else result

,comstock_building_type,sample_count,units_count,rows_per_sample,electricity.total.energy_consumption,natural_gas.total.energy_consumption
0,FullServiceRestaurant,2056,4222.612917,35040,1.067478e+09,9.071796e+08
1,LargeOffice,22,8.927070,35040,6.772292e+06,4.947173e+04
2,MediumOffice,527,603.917258,35040,1.684457e+08,3.612400e+06
3,Outpatient,408,1387.428142,35040,1.513752e+08,1.430494e+07
4,PrimarySchool,475,1108.926331,35040,2.838701e+08,5.207440e+07

## `inv_upgrade1_applied_ts_monthly_by_building_type`

Three-way invariant: ts-monthly leg, upgrade 1, applied_only=True. Two fuels.

In [9]:
result = bsq.query(
    enduses=['out.electricity.total.energy_consumption', 'out.natural_gas.total.energy_consumption'],
    upgrade_id='1',
    applied_only=True,
    annual_only=False,
    timestamp_grouping_func='month',
    group_by=['comstock_building_type', 'time'],
    restrict=[('state', ['CO'])],
)
result.head() if hasattr(result, 'head') else result

,comstock_building_type,timestamp,sample_count,units_count,rows_per_sample,electricity.total.energy_consumption,natural_gas.total.energy_consumption
0,FullServiceRestaurant,2018-01-01,2056,4222.612917,2976,1.041671e+08,8.183587e+07
1,FullServiceRestaurant,2018-02-01,2056,4222.612917,2688,1.016340e+08,7.482833e+07
2,FullServiceRestaurant,2018-03-01,2056,4222.612917,2976,8.463370e+07,7.862536e+07
3,FullServiceRestaurant,2018-04-01,2056,4222.612917,2880,7.864523e+07,7.464483e+07
4,FullServiceRestaurant,2018-05-01,2056,4222.612917,2976,8.022208e+07,7.459019e+07

## `inv_upgrade1_applied_in_1_2_annual_by_building_type`

Three-way invariant: annual leg, upgrade 1, applied_only=True, applied_in=[1,2]. Two fuels.

In [10]:
result = bsq.query(
    enduses=['out.electricity.total.energy_consumption..kwh', 'out.natural_gas.total.energy_consumption..kwh'],
    upgrade_id='1',
    applied_only=True,
    applied_in=[1, 2],
    group_by=['comstock_building_type'],
    restrict=[('state', ['CO'])],
)
result.head() if hasattr(result, 'head') else result

,comstock_building_type,sample_count,units_count,electricity.total.energy_consumption..kwh,natural_gas.total.energy_consumption..kwh
0,FullServiceRestaurant,2056,4222.612917,1.067479e+09,9.065733e+08
1,LargeOffice,22,8.927070,6.772289e+06,4.943943e+04
2,MediumOffice,527,603.917258,1.684458e+08,3.609832e+06
3,Outpatient,400,1378.302123,1.456331e+08,1.386505e+07
4,PrimarySchool,475,1108.926331,2.838699e+08,5.203942e+07

## `inv_upgrade1_applied_in_1_2_ts_year_by_building_type`

Three-way invariant: ts-year-collapse leg, upgrade 1, applied_only=True, applied_in=[1,2]. Two fuels.

In [11]:
result = bsq.query(
    enduses=['out.electricity.total.energy_consumption', 'out.natural_gas.total.energy_consumption'],
    upgrade_id='1',
    applied_only=True,
    applied_in=[1, 2],
    annual_only=False,
    timestamp_grouping_func='year',
    group_by=['comstock_building_type'],
    restrict=[('state', ['CO'])],
)
result.head() if hasattr(result, 'head') else result

,comstock_building_type,sample_count,units_count,rows_per_sample,electricity.total.energy_consumption,natural_gas.total.energy_consumption
0,FullServiceRestaurant,2056,4222.612917,35040,1.067478e+09,9.071796e+08
1,LargeOffice,22,8.927070,35040,6.772292e+06,4.947173e+04
2,MediumOffice,527,603.917258,35040,1.684457e+08,3.612400e+06
3,Outpatient,400,1378.302123,35040,1.456332e+08,1.387436e+07
4,PrimarySchool,475,1108.926331,35040,2.838701e+08,5.207440e+07

## `inv_upgrade1_applied_in_1_2_ts_monthly_by_building_type`

Three-way invariant: ts-monthly leg, upgrade 1, applied_only=True, applied_in=[1,2]. Two fuels.

In [12]:
result = bsq.query(
    enduses=['out.electricity.total.energy_consumption', 'out.natural_gas.total.energy_consumption'],
    upgrade_id='1',
    applied_only=True,
    applied_in=[1, 2],
    annual_only=False,
    timestamp_grouping_func='month',
    group_by=['comstock_building_type', 'time'],
    restrict=[('state', ['CO'])],
)
result.head() if hasattr(result, 'head') else result

,comstock_building_type,timestamp,sample_count,units_count,rows_per_sample,electricity.total.energy_consumption,natural_gas.total.energy_consumption
0,FullServiceRestaurant,2018-01-01,2056,4222.612917,2976,1.041671e+08,8.183587e+07
1,FullServiceRestaurant,2018-02-01,2056,4222.612917,2688,1.016340e+08,7.482833e+07
2,FullServiceRestaurant,2018-03-01,2056,4222.612917,2976,8.463370e+07,7.862536e+07
3,FullServiceRestaurant,2018-04-01,2056,4222.612917,2880,7.864523e+07,7.464483e+07
4,FullServiceRestaurant,2018-05-01,2056,4222.612917,2976,8.022208e+07,7.459019e+07